version: "3"

services:
  minio:
    container_name: minio
    image: 'bitnami/minio:latest'
    volumes:
      - 'minio_data:/data'
    ports:
      - "9000:9000"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_USE_SSL: "${MINIO_USE_SSL}"
      MINIO_DEFAULT_BUCKETS: "${MINIO_BUCKET_NAME}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  rest-server:
    build:
      context: ./
      dockerfile: ./restServer/Dockerfile
    container_name: restServer
    volumes:
      - storage:/data/:ro
    ports:
      - "8081:8080"
    networks:
      - internalNetwork
      - externalNetwork
    depends_on:
      minio:
        condition: service_started
    #environment:
    restart: always

volumes:
  minio_data:

networks:
    internalNetwork:
        driver: bridge
    externalNetwork:
        name: fema
